services:
  - type: web
    name: movie-catalogue-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: MONGODB_URI
        value: mongodb+srv://utkarshrana40_db_user:zrYQHcT4WjoCWQna@cluster0.tpbyi5g.mongodb.net/?appName=Cluster0
      - key: PORT
        value: 5000
      - key: JWT_SECRET
        value: secret_key_123
      - key: HIANIME_API_BASE_URL
        sync: false
      - key: STREAM_PROXY_SECRET
        generateValue: true
      - key: GOOGLE_APPLICATION_CREDENTIALS
        value: ./firebase-service-account.json
